# Generated by Django 3.0.4 on 2020-03-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0002_auto_20200312_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
